# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Package

on:
  pull_request:
    branches: [master]
    types:
      - closed
jobs:
  publish-npm:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install 🔧
        run: npm install --legacy-peer-deps

      - name: Build 🏗️
        run: npm run build:lib

      - name: Publish Npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.KNE_PACKAGE_PUBLISH}}
        run: npm publish --access=public
      ## 请修改对应的packageName后取消以下命令的注释
      - name: Sync To Cnpm
        run: npm i -g cnpm && cnpm sync @kne/react-form
